language: cpp

dist: bionic

addons:
  apt:
    packages:
    - gettext 
    - autopoint 
    - automake 
    - autoconf 
    - intltool 
    - libc6-dev 
    - libjansson-dev 
    - libgtk-3-dev 
    - libgtk2.0-dev 
    - libasound2-dev 
    - ffmpeg 
    - libavcodec-dev 
    - libavdevice-dev 
    - libavfilter-dev 
    - libavformat-dev 
    - libavformat57 
    - libavresample-dev 
    - libdbus-1-dev 
    - libpulse-dev 
    - libmad0-dev 
    - libmpg123-dev 
    - libvorbis-dev 
    - libopus-dev 
    - opus-tools 
    - libopusfile-dev 
    - libogg-dev 
    - libflac-dev 
    - libwavpack-dev 
    - libsndfile1-dev 
    - libcdio-dev 
    - libcdio-cdda-dev 
    - libcdio-cdda2 
    - libcdparanoia-dev 
    - libcddb2-dev 
    - oss-compat 
    - oss4-dev 
    - libimlib2-dev 
    - libsamplerate0-dev 
    - libfaad-dev 
    - libzip-dev 
    - zip 
    - yasm 
    - libglib2.0-bin 
    - fakeroot
  homebrew:
    packages:
    - intltool
    - libtool
    - gawk
    - jansson
    - libzip
    - yasm
    - gtk+3
    - glib
  sonarcloud:
    organization: "cartoonfan"
    token:
      secure: "GclhC/mYAMgyHTOhPPkcuq00AasytSpiY78U+bf/eUEnCZHJcSn8JModTa79r8Mb5m2i7gTMPDWgTNRxCgNJL7LPQ6Orq/n3ZawaOW1dnW5NbebJV8aXzUp9j2lL5ojYjxQzTrCCwdRFkA2LO07CUNDY0VfQt/wruieQ8CTTwADxuyLNmBNjAZra6E+k7A7hdsn7EeadSstxaHse+Mq2K4PZJ65KJdJz/+g3WnV76asJH3/8YIG8YcA1HvDKvddtJmqHfwi9l0+0Zf9GFxEXI4+Pur5vF/PddBsH3LCEtvUQqRia9SYavH3irgrTjwDfPiD2GwozAbW9eNiWJDI2dKVceY7k36tVV81KBSFZNXwfeFmu6frjpkGTXD9UyScV8lYo4o9y/UnDBo4ISPLvpKkBrDlqto9bMhq1OoHouXL+k7h0AhfT/TM3l0fe81R3hw7+6js2XNRpUSNwCvfSRW7eUgBzYSBdfSmgO0sfIH+PVYsRvxPiwdV9TbyEeL+QXsZ1TOhQecZTloGdgeuEDb8SSsyioZDxn7SGz8I58vid1RYoEm5UZjQ7CqrilAT319qwEv02exvvSXRyyTIg2K7cSd6wRKqAcoJRNUwcf4qY0orpyaJAt8JJmD6GBHTOfufgyFeYtaGbzmNcMJp36rMhSl/OMOy63EZzdMkYndw="

compiler:
  - gcc
  - clang

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.5

script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - ./autogen.sh
  - ./configure
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

after_success:
    - ./travis/upload.sh
    
cache:
  directories:
    - '$HOME/.sonar/cache'
